#  Basé sur :  https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough
#        Front: nginx: mcr.microsoft.com/azuredocs/azure-vote-front:v1
#        Back:  redis: mcr.microsoft.com/oss/bitnami/redis:6.0.8

#  frontend : nginx
#  backend  : redis:6.0.8

# Acces via service K8S :   http://[IP LB]

# Appli dans:  /app
# Fichier de conf : /app/config_file.cfg  :   permet d'afficher le nom du pod ou pas avec la variable "hostname"
# Configurer l'affichage de la version de l'appli dans le portail web : dans /app/main.py

# Installer vim dans le container:
#  - apt update
#  - apt install vim

#  kubectl scale deployment vote-frontend --replicas=2


apiVersion: v1
kind: Service
metadata:
  name: vote-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: vote-frontend






