apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tito-fe-$${TITO_VERSION_LOWER}
  name: deployment-$${TITO_VERSION_LOWER}
  namespace: default
spec:
  minReadySeconds: 0
  replicas: 2
  selector:
    matchLabels:
      app: tito-fe-$${TITO_VERSION_LOWER}
  template:
    metadata:
      labels:
        app: tito-fe-$${TITO_VERSION_LOWER}
    spec:
      containers:
        - name: tito-fe-container   # Nom du container docker : k8s_tito-fe-container.<ID>  (docker ps)
          image: vmeoc/tito-fe:V1.9.4
          env:
          - name: $${TITO_VERSION}
            value: V2.4
          - name: PROXY_NAME
            value: wvfp.cpod-vrealizesuite.az-demo.shwrfr.com
          - name: PROXY_PORT
            value: "2878"
