apiVersion: v1
kind: Service
metadata:
  name: tito-fe-svc    # nom du Service
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
  selector:
    app: tito-fe-$${TITO_VERSION_LOWER}    #tito-fe-v0.5
