apiVersion: v1
kind: Service
metadata:
  name: lamp-apache
  namespace: lamp-k8s
  labels:
    app.kubernetes.io/name: apache
    app.kubernetes.io/instance: lamp-apache
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
  selector:
    app.kubernetes.io/name: apache
    app.kubernetes.io/instance: lamp-apache
