apiVersion: v1
kind: Service
metadata:
  name: lamp-apache
  namespace: lamp-k8s
  labels:
    app.kubernetes.io/name: apache
    helm.sh/chart: apache-8.5.1
    app.kubernetes.io/instance: lamp-apache
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app.kubernetes.io/name: apache
    app.kubernetes.io/instance: lamp-apache
