apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-apache
  namespace: lamp-k8s
  labels:
    app.kubernetes.io/name: apache
    helm.sh/chart: apache-8.5.1
    app.kubernetes.io/instance: lamp-apache
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: apache
      app.kubernetes.io/instance: lamp-apache
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apache
        helm.sh/chart: apache-8.5.1
        app.kubernetes.io/instance: lamp-apache
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: apache
          image: docker.io/bitnami/apache:2.4.46-debian-10-r218
          imagePullPolicy: "IfNotPresent"
          env:
            - name: BITNAMI_DEBUG
              value: "false"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: htdocs
              mountPath: /app
            - name: vhosts
              mountPath: /vhosts
      volumes:
        - name: vhosts
          configMap:
            name: apache-conf
