apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-conf
  namespace: lamp-k8s
data:
  apache.conf: |
    LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so
    <VirtualHost *:8080>
      DocumentRoot "/app"
      ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://lamp-php-fpm:9000/app/$1
      RedirectMatch 204 /healthcheck.html
      <Directory "/app">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
        DirectoryIndex poc.php
      </Directory>
    </VirtualHost>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-healthcheck
  namespace: lamp-k8s
data:
  healthcheck.html: |
    <html>
      <head><title>Up and running</title></head>
      <body>I'm alive</body>
    </html>
