apiVersion: v1
kind: Service
metadata:
  labels:
    app: lamp-php-fpm
  name: lamp-php-fpm
  namespace: lamp-k8s
spec:
  ports:
  - port: 9000
  selector:
    app: lamp-php-fpm
    tier: backend
  type: ClusterIP
