apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:

      containers:
      # application
      - name: nginx1
        image: alexfr75/nginx:1.1
        ports:
        - name: http
          containerPort: 80
      

---


apiVersion: v1
kind: Service
metadata:
  name: nginx-svc1
spec:
  type: NodePort
  ports:
  - name: http
    targetPort : 80    # port dans le container !! (INDISPENSABLE pour que cela fonctionne)
    nodePort: 31281    # pour forcer le port expose par le service en externe (sinon alÃÂ©oire) (LB nord/sud)
    port: 31181        # port interne pour le clusterIP (LB est/ouest)
  selector:
    app: nginx1

