

apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config-for-nginx
  namespace: default
data:
  nginx.conf: |
    [[inputs.nginx]]
      ## An array of Nginx status URI to gather stats.
      urls = ["http://$HOSTNAME/basic_status"]

      ## Optional SSL Config
      # ssl_ca = "/path/to/ca.pem"
      # ssl_cert = "/path/to/cert.pem"
      # ssl_key = "/path/to/key.pem"
      ## Use SSL but skip chain & host verification
      # insecure_skip_verify = false

      ## HTTP response timeout (default: 5s)
      response_timeout = "30s"

      # Specify optional tags to be applied to all metrics for this plugin
      # NOTE: Order matters, this needs to be at the end of the plugin definition
      # [[inputs.nginx.tags]]
        # tag1 = "foo"
        # tag2 = "bar"


---


apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config-for-nginx-tail
  namespace: default
data:
  tail.conf: |
    [[inputs.tail]]
    files = ["/var/log/nginx/access.log"]

    ## Read file from beginning.
    from_beginning = false

    ## Whether file is a named pipe
    pipe = false

    ## measurement name prefix (to keep "tail" and "nginx" plugin metrics insync)
    name_prefix = "nginx."

    ## Data format to consume.
    data_format = "grok"

    grok_patterns = ["%{COMBINED_LOG_FORMAT}"]

    ## Add tags to keep in sync with NGINX Server metrics
    [inputs.tail.tags]
      server = "<nginx_server>"
      port = "<port>"

