
# This ClusterRoleBinding associates the ServiceAccount "default" (which is in namespace "tito") with the ClusterRole "cluster-admin" (exist by default)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fullrightstodefault
subjects:
- kind: ServiceAccount
  namespace: tito
  name: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""


---


kind: Namespace
apiVersion: v1
metadata:
  name: tito
  labels:
    name: tito


---


apiVersion: v1
kind: Service
metadata:
  name: tito-fe-svc
  namespace: tito
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
  selector:
    app: tito-fe


---


apiVersion: v1
kind: ReplicationController
metadata:
  name: tito-fe-rc
  namespace: tito
spec:
  replicas: 2
  selector:
    app: tito-fe
  template:
    metadata:
      labels:
        app: tito-fe
    spec:
      containers:
        - name: tito-fe-container
          image: vmeoc/tito-fe:V1.9.4
          env:
          - name: TITO_VERSION
            value: V2.4
