apiVersion: v1
data:
  apache.conf: |
    LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so
    <VirtualHost *:8080>
      DocumentRoot "/app"
      ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://lamp-php-fpm:9000/app/$1
      RedirectMatch 204 /healthcheck.html
      <Directory "/app">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
        DirectoryIndex poc.php
      </Directory>
    </VirtualHost>
kind: ConfigMap
metadata:
  name: apache-conf
  namespace: lamp-k8s
---
apiVersion: v1
data:
  healthcheck.html: |
    <html>
      <head><title>Up and running</title></head>
      <body>I'm alive</body>
    </html>
kind: ConfigMap
metadata:
  name: apache-healthcheck
  namespace: lamp-k8s
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lamp-php-fpm
  name: lamp-php-fpm
  namespace: lamp-k8s
spec:
  ports:
  - port: 9000
  selector:
    app: lamp-php-fpm
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lamp-php-fpm
  name: lamp-php-fpm
  namespace: lamp-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lamp-php-fpm
      tier: backend
  template:
    metadata:
      labels:
        app: lamp-php-fpm
        tier: backend
    spec:      
      containers:
      - image: alexandreroman/ndc-php@sha256:3aa56f1107b925e56fff23003a6ee5fb905646b63de914fa8bafd150df27d65f
        name: lamp-php-fpm
        ports:
        - containerPort: 9000
          name: lamp-php-fpm
        volumeMounts:
        - mountPath: /app
          name: lamp-phpcontent
      volumes:
      - name: lamp-phpcontent
        configMap:
          name: php-content
        