apiVersion: v1
kind: ReplicationController
metadata:
  name: tito-fe-rc-$${TITO_INSTANCE} # nom du RC et des PODS
spec:
  replicas: $${TITO_REPLICA}
  selector:
    app: tito-fe
  template:
    metadata:
      #generateName: tito-fe-pod-   # INUTILE car surcharge par: nom du RC-xxxxx
      labels:
        app: tito-fe
    spec:
      containers:
        - name: tito-fe-container   # Nom du container docker : k8s_tito-fe-container.<ID>  (docker ps)
          image: vmeoc/tito-fe:V2.4
          env:
          - name: TITO_VERSION
            value: $${TITO_VERSION}
          - name: PROXY_NAME
            value: $${PROXY_NAME}
          - name: PROXY_PORT
            value: "2878"
