apiVersion: v1
kind: ReplicationController
metadata:
  name: tito-fe-rc                  # nom du RC et des PODS
spec:
  replicas: 2
  selector:
    app: tito-fe
  template:
    metadata:
      #generateName: tito-fe-pod-   # INUTILE car surcharge par: nom du RC-xxxxx
      labels:
        app: tito-fe
    spec:
      containers:
        - name: tito-fe-container   # Nom du container docker : k8s_tito-fe-container.<ID>  (docker ps)
          image: vmeoc/tito-fe:V1.9.4
          env:
          - name: TITO_VERSION
            value: V2.4
          - name: PROXY_NAME
            value: wvfp.cpod-vrealizesuite.az-demo.shwrfr.com
          - name: PROXY_PORT
            value: "2878"


---


apiVersion: v1
kind: Service
metadata:
  name: tito-fe-svc    # nom du Service
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
  selector:
    app: tito-fe
